owner: logiqbal
repo: upstatus

sites:
  - name: Ubuntu.com
    url: https://ubuntu.com
  - name: Ubuntu.com engage index
    url: https://ubuntu.com/engage
  - name: Ubuntu.com takeovers index
    url: https://ubuntu.com/takeovers
  - name: Ubuntu.com blog
    url: https://ubuntu.com/blog
  - name: Ubuntu.com blog post
    url: https://ubuntu.com/blog/design-and-web-team-summary-29-december-2020
  - name: Ubuntu.com advantage
    url: https://ubuntu.com/advantage
  - name: Ubuntu.com tutorials
    url: https://ubuntu.com/tutorials
  - name: Ubuntu.com tutorial
    url: https://ubuntu.com/tutorials/how-to-install-ubuntu-desktop-on-raspberry-pi-4#1-overview
  - name: Ubuntu.com server docs
    url: https://ubuntu.com/server/docs
  - name: Ubuntu.com kubernetes docs
    url: https://ubuntu.com/kubernetes/docs
  - name: Ubuntu.com Ceph docs
    url: https://ubuntu.com/ceph/docs
  - name: Ubuntu.com smart start guide
    url: https://ubuntu.com/smartstart/guide
  - name: Ubuntu.com appliances portfolio
    url: https://ubuntu.com/appliance/portfolio
  - name: Ubuntu.com appliance page
    url: https://ubuntu.com/appliance/openhab
  - name: Ubuntu.com CVE list
    url: https://ubuntu.com/security/cve
  - name: Ubuntu.com CVE page
    url: https://ubuntu.com/security/CVE-2020-15180
  - name: Ubuntu.com USN list
    url: https://ubuntu.com/security/notices
  - name: Ubuntu.com USN page
    url: https://ubuntu.com/security/notices/USN-4697-2
  - name: Ubuntu Security API - CVEs
    url: https://ubuntu.com/security/cves.json
  - name: Ubuntu Security API - Notices
    url: https://ubuntu.com/security/notices.json
  - name: Ubuntu Security API - CVE page
    url: https://ubuntu.com/security/cves/CVE-2020-15180.json
  - name: Ubuntu Security API - USN page
    url: https://ubuntu.com/security/notices/USN-4697-2.json
  - name: Snapcraft.io
    url: https://snapcraft.io
  - name: Snapcraft.io store page
    url: https://snapcraft.io/store
  - name: Charmhub.io
    url: https://charmhub.io
  - name: Vanilla Framework
    url: https://vanillaframework.io
  - name: JAAS.ai
    url: https://jaas.ai
  - name: JAAS Dashboard
    url: https://jaas.ai/models
  - name: anbox-cloud.io
    url: https://anbox-cloud.io
  - name: canonical.com
    url: https://canonical.com
  - name: certification.ubuntu.com
    url: https://certification.ubuntu.com
  - name: charmed-osm.com
    url: https://charmed-osm.com
  - name: cn.ubuntu.com
    url: https://cn.ubuntu.com
  - name: dqlite.io
    url: https://dqlite.io
  - name: jp.ubuntu.com
    url: https://jp.ubuntu.com
  - name: juju.is
    url: https://juju.is
  - name: kubeflow-news.com
    url: https://kubeflow-news.com
  - name: maas.io
    url: https://maas.io
  - name: maas.io docs
    url: https://maas.io/docs
  - name: microk8s.io
    url: https://microk8s.io
  - name: microk8s.io/docs
    url: https://microk8s.io/docs/release-notes
  - name: multipass.run
    url: https://multipass.run
  - name: mir-server.io
    url: https://mir-server.io
  - name: microstack.run
    url: https://microstack.run
  - name: netplan.io
    url: https://netplan.io

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /upstatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Status
  introTitle: "**Uptime Status**"
  introMessage: This page shows the status of the services and projects I'm monitoring
  navbar:
    - title: Status
      href: /upstatus
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
