owner: logiqbal
repo: upstatus

sites:
  - name: Ubuntu.com
    url: https://ubuntu.com
  - name: Monitor 1
    url: $API_URL

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /upstatus
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Status
  introTitle: "**Uptime Status**"
  introMessage: This page shows the status of the services and projects I'm monitoring
  navbar:
    - title: Status
      href: /upstatus
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
